# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

orbs:
  heroku: circleci/heroku@2.0.0

jobs:
  build-and-test:
    docker:
      - image: denoland/deno:1.37.1
    steps:
      - checkout
      - run:
          name: "Setup custom environment variables"
          command: echo 'export HEROKU_APP_NAME="deno-heroku-circleci"' >> "$BASH_ENV"
      - run: |
          deno test --allow-net server.test.ts
          echo $HEROKU_APP_NAME
      - run:
          name: "What branch am I on now?"
          command: echo $CIRCLE_BRANCH
      - run:
          name: "Print an env var stored in the Project"
          command: echo ${HEROKU_APP_NAME}
workflows:
  sample:
    jobs:
      - build-and-test
      - heroku/deploy-via-git:
          force: true # this parameter instructs the push to use a force flag when pushing to the heroku remote, see: https://devcenter.heroku.com/articles/git
          requires:
            - build-and-test
